# MoreGameRules configuration file
# Developed by lucasof (https://kzoflabs.tk)

anti-soil-trampling: false

no-hunger: false

unbreakable-items: false

anti-modify-blocks: false
bypass-with-permission: false

invincible: false


no-join-quit-messages: false

only-mob-spawners: false
nature-spawn-on-world: "insert-world-name-here"
