# MoreGameRules configuration file
# Developed by Kzof Labs (https://kzoflabs.tk)
# Version: 1.0-SNAPSHOT

# When you trample on Wheat for example it won't change to dirt
anti-soil-trampling: false

# Removes Hunger
no-hunger: false

# Make all items unbreakable
unbreakable-items: false

# Prevent players from breaking or placing blocks
anti-modify-blocks: false

# Makes you invincible
invincible: false

# Removes Join/Quit messages (Player joined the game)
no-join-quit-messages: false

# Allows you to fly (Coming Soon - If you know how to do it, please open a Pull Request)
fly: false

# End of the config file o: