# MoreGameRules configuration file
# Developed by Kzof Labs (https://kzoflabs.tk)
# Version: 1.0-SNAPSHOT

# When you trample on Wheat for example it won't change to dirt
anti-soil-trampling: false

# Removes Hunger
no-hunger: false

# Make all items unbreakable
unbreakable-items: false

# Allows you to fly (Survival-Mode) - Coming Soon
fly: false

# Prevent players from breaking blocks - Coming Soon
blocks-breakable: false

# End of the config file o: