name: MoreGameRules
version: 1.1
main: tk.kzoflabs.Main
author: lucazof
commands:
  moregamerules:
    description: "MoreGameRules information"
    aliases: ["mgr", "gmr"]
    permission: "moregamerules.admin"
    permission-message: "§cYou don't have permission!"